apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: #DEPLOYMENT-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: #SERVICE
        version: #VERSION
        runtime: #RUNTIME
        mp-version: #MPVERSION
    spec:
      containers:
      - name: #SERVICE-#RUNTIME
        image: #PREFIX/#DEPLOYMENT:#MPVERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: #SERVICE-config
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080/health/live
          initialDelaySeconds: 120
          periodSeconds: 10
